//=========================================================
// src/Interupts.c: generated by Hardware Configurator
//
// This file will be regenerated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!
//=========================================================

         
// USER INCLUDES			
#include <SI_EFM8BB1_Register_Enums.h>
#include <stdio.h>

//-----------------------------------------------------------------------------
// ADC0EOC_ISR
//-----------------------------------------------------------------------------
//
// ADC0EOC ISR Content goes here. Remember to clear flag bits:
// ADC0CN0::ADINT (Conversion Complete Interrupt Flag)
//
// This ISR is called after each ADC conversion which is triggered by rising edge of CNVSTR.
//
//-----------------------------------------------------------------------------
SI_INTERRUPT (ADC0EOC_ISR, ADC0EOC_IRQn)
{
   static uint16_t ADC0_i;
   static uint16_t measurements = 10; // Measurement counter

   uint8_t adc_val_lower;
   uint8_t adc_val_upper;

   ADC0CN0_ADINT = 0;                  // Clear ADC0 conv. complete flag

   ADC0_i = ADC0;
   measurements--;

   if(measurements == 0)
   {
	  measurements = 10;

	  adc_val_lower = ADC0_i & 0xFF;
	  adc_val_upper = (ADC0_i >> 8) & 0x03;

	  putchar( 0xAA );
	  putchar( adc_val_upper );
	  putchar( adc_val_lower );
   }
}


//-----------------------------------------------------------------------------
// TIMER2_ISR
//-----------------------------------------------------------------------------
//
// TIMER2 ISR Content goes here. Remember to clear flag bits:
// TMR2CN0::TF2H (Timer # High Byte Overflow Flag)
// TMR2CN0::TF2L (Timer # Low Byte Overflow Flag)
//
//-----------------------------------------------------------------------------
SI_INTERRUPT (TIMER2_ISR, TIMER2_IRQn)
{

}


